### ISSUE TITLE
More specific error message

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown-cli#1]
When run in the commandline, the parser throws a detailed error message when encountering a problem. Would it be possible to include in this error message the number of the line in the original markdown document which is responsible for the error?

That would allow the user to see where something is going wrong and to fix the argdown code more quickly.

**Comment by christianvoigt** [comment]
This should be the task of a linter plugin that is also needed for better feedback in Atom.

**Comment by christianvoigt** [comment]
With argdown-cli 0.4.0 (argdown parser 0.5.0) this is now implemented in the new ArgdownErrorMessageProvider. Further proposals for better error reporting should be posted as separate issues in the main argdown repository.
