### ISSUE TITLE
Export subfolders not in source file directory

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown-cli#2]
The subfolders (dot, html, etc.) which store the export files are created in the directory that contains the source file but in the directory from which argdown is actually called. Wouldn't it make sense to create those export directories whereever the sourcefile is located?

**Comment by christianvoigt** [comment]
Yes, that would be better. For now you can specify the input and output folders explicitely using

````bash
argdown dot [glob pattern for files to process] [output folder]
````

**Comment by christianvoigt** [comment]
On second thought I am not so sure about this anymore. For example, let's say you have a project directory in which you want to create a html folder with exported html files. Your Argdown files are in a "src" folder in your project directory and you are calling `argdown html ./src/` from the project directory. The current behavior will correctly create the html folder while changing this behavior would make it necessary to use `argdown html ./src ./html`

**Comment by ggbetz** [comment]
I see. Makes sense. As one can specify the output folder explicitly (as you said above), the current implementation actually works fine with me.
