### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown-cli#3]
Wildcards does not fully work:
```
Macintosh-4:tests2017 user$ argdown dot *.argdown
{ Error: EEXIST: file already exists, mkdir '/Users/.../tests2017/Test-0001.argdown'
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/Users/.../tests2017/Test-0001.argdown' }
```

**Comment by christianvoigt** [comment]
This is a documentation error. Please use quotes around the wildcard, otherwise the shell will 'expand' the wildcard into a space-separated list of files. If there are more than one file, the second one will be interpreted as the output folder, which leads to the error you encountered.

````
argdown dot '*.argdown'
```
