### ISSUE TITLE
-w Option doesn't work

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown-cli#4]
The commands `argdown -w dot argdown08.argdown` or `argdown dot argdown08.argdown -w` don't work (Mac). The program is running in the shell and has to be stopped with ctrl+c. But `argdown08.argdown` is not parsed and exported to a dot file -- neither initially nor upon change. The command `argdown dot argdown08.argdown` works fine, though.

(Is it somehow guaranteed that https://github.com/yargs/yargs is installed? How can I verify that?)

**Comment by christianvoigt** [comment]
Could you update and try again? I just released a patch for some path/config issues, maybe this is related. Using the latest version I successfully used the -w option with the dot export.

Please also check if you have argdown.config.js loaded with watch set to false.

**Comment by christianvoigt** [comment]
closing this. @ggbetz had an outdated version of argdown-cli installed.
